#!/usr/bin/env bash
#using case instead of if

opening(){
numbers=1
  while [ $numbers -le 20 ]; do
  case $numbers in
       4) 
	       echo "$numbers"
	       echo "bad luck from China"
       ;;
       9) 
	       echo "$numbers"
	       echo "bad luck from Japan"
       ;;
       17)
	       echo "$numbers"
	       echo "bad luck from Italy"
       ;;
       *) echo "$numbers"
       ;;
  esac
numbers=$((numbers + 1))
done
}
opening
